-- 🌙 APNAGATE - COMPLETE PRODUCTION SCHEMA
-- Date: December 2025
-- Description: This schema defines the structure for a modern, secure society management system.
--              It includes Users, Roles, Visitors, Complaints, Notices, SOS, and RLS Policies.

-- ================================================================================================
-- 1. EXTENSIONS & SETUP
-- ================================================================================================

-- Enable UUID extension for unique identifiers
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ================================================================================================
-- 2. TABLES
-- ================================================================================================

-- 👤 PROFILES
-- Stores user details linked to Supabase Auth
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY, -- Links to Auth User
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    role TEXT CHECK (role IN ('resident', 'admin', 'guard', 'staff')), -- Defined Roles
    wing TEXT,        -- E.g., 'A', 'B'
    flat_number TEXT, -- E.g., '101', '1002'
    photo_url TEXT,   -- Avatar URL
    user_type TEXT CHECK (user_type IN ('owner', 'tenant', 'family')), -- Resident Sub-type
    owner_id UUID REFERENCES public.profiles(id), -- If family/tenant, links to primary owner
    fcm_token TEXT,   -- Firebase Cloud Messaging Token (for legacy/android)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 📝 SOCIETY CONFIGURATION
-- Stores dynamic building structure
CREATE TABLE IF NOT EXISTS public.society_config (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    wings TEXT[] DEFAULT '{}', -- Array of Wing Names: ['A', 'B']
    floors INTEGER DEFAULT 0,  -- Number of floors per wing
    flats_per_floor INTEGER DEFAULT 0, -- Flats per floor
    amenities TEXT[] DEFAULT '{}', -- List of amenities
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 🚶 VISITORS
-- Logs every visitor entry/exit
CREATE TABLE IF NOT EXISTS public.visitors (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    resident_id UUID REFERENCES public.profiles(id), -- Who approved/is being visited
    guard_id UUID REFERENCES public.profiles(id),    -- Guard who created entry
    visitor_name TEXT NOT NULL,
    visitor_phone TEXT,
    photo_url TEXT,
    purpose TEXT CHECK (purpose IN ('Delivery', 'Guest', 'Cab', 'Service', 'Other', 'Guest Pass')),
    wing TEXT NOT NULL,
    flat_number TEXT NOT NULL,
    status TEXT CHECK (status IN ('pending', 'approved', 'rejected', 'inside', 'entered', 'exited', 'denied')),
    entry_time TIMESTAMP WITH TIME ZONE,
    exit_time TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 🎟️ GUEST PASSES
-- Pre-approved entry tokens generated by residents
CREATE TABLE IF NOT EXISTS public.guest_passes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    resident_id UUID REFERENCES public.profiles(id) NOT NULL,
    visitor_name TEXT NOT NULL,
    token TEXT UNIQUE NOT NULL, -- The scannable code/token
    valid_until TIMESTAMP WITH TIME ZONE NOT NULL,
    is_used BOOLEAN DEFAULT FALSE,
    used_at TIMESTAMP WITH TIME ZONE,
    guest_count INTEGER DEFAULT 1,
    additional_info TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 📢 NOTICES
-- Announcements from Admins
CREATE TABLE IF NOT EXISTS public.notices (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    type TEXT CHECK (type IN ('general', 'alert', 'event', 'maintenance')),
    created_by UUID REFERENCES public.profiles(id),
    expires_at TIMESTAMP WITH TIME ZONE,
    attachment_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ⚠️ COMPLAINTS
-- Issues reported by residents
CREATE TABLE IF NOT EXISTS public.complaints (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    ticket_id TEXT UNIQUE, -- User-friendly ID like #CG-1234
    resident_id UUID REFERENCES public.profiles(id) NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT CHECK (category IN ('plumbing', 'electrical', 'security', 'cleaning', 'other')),
    status TEXT CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')) DEFAULT 'open',
    photo_urls TEXT[] DEFAULT '{}', -- Array of image URLs
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 💬 COMPLAINT CHATS
-- Discussion thread for specific complaints
CREATE TABLE IF NOT EXISTS public.complaint_chats (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    complaint_id UUID REFERENCES public.complaints(id) ON DELETE CASCADE NOT NULL,
    sender_id UUID REFERENCES public.profiles(id) NOT NULL,
    message TEXT,
    image_url TEXT,
    is_admin BOOLEAN DEFAULT FALSE, -- True if sent by admin
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 🚨 SOS ALERTS
-- Emergency signals triggered by residents
CREATE TABLE IF NOT EXISTS public.sos_alerts (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    resident_id UUID REFERENCES public.profiles(id) NOT NULL,
    resident_name TEXT, -- Cached for speed
    wing TEXT,
    flat_number TEXT,
    status TEXT CHECK (status IN ('active', 'resolved', 'false_alarm')) DEFAULT 'active',
    resolved_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 🔔 NOTIFICATIONS (Historical)
-- Stores notification history for the "Bell" icon
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    data JSONB, -- Stores metadata like {visitor_id: '...', type: 'visitor'}
    read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 🧹 HOUSEHOLD / FAMILY
-- Registry of family members and tenants
CREATE TABLE IF NOT EXISTS public.household_registry (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    owner_id UUID REFERENCES public.profiles(id) NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    relation TEXT, -- Parent, Child, Spouse
    role TEXT CHECK (role IN ('family', 'tenant')),
    wing TEXT,
    flat_number TEXT,
    email TEXT,
    photo_url TEXT,
    is_registered BOOLEAN DEFAULT FALSE, -- True if they have their own App Login
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 👷 DAILY HELP (Maids, Drivers)
CREATE TABLE IF NOT EXISTS public.daily_help (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    owner_id UUID REFERENCES public.profiles(id) NOT NULL, -- Primary employer
    name TEXT NOT NULL,
    role TEXT, -- Clean, Cook, Driver
    phone TEXT,
    photo_url TEXT,
    is_present BOOLEAN DEFAULT FALSE, -- Currently inside society?
    last_entry_time TIMESTAMP WITH TIME ZONE,
    last_exit_time TIMESTAMP WITH TIME ZONE,
    wing TEXT,
    flat_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 📋 SERVICE PROVIDERS (Directory)
-- Admin managed list of electricians, plumbers, etc.
CREATE TABLE IF NOT EXISTS public.service_providers (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- Plumber, Carpenter, etc.
    phone TEXT NOT NULL,
    description TEXT,
    rating NUMERIC(2,1) DEFAULT 5.0,
    status TEXT DEFAULT 'active', -- entry status
    last_active TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 📜 STAFF LOGS
-- Attendance logs for Daily Help and Service Providers
CREATE TABLE IF NOT EXISTS public.staff_attendance_logs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    staff_id UUID REFERENCES public.daily_help(id) ON DELETE CASCADE,
    owner_id UUID REFERENCES public.profiles(id),
    action TEXT CHECK (action IN ('entry', 'exit')),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ================================================================================================
-- 3. ROW LEVEL SECURITY (RLS) POLICIES
-- ================================================================================================
-- 🛡️ Secure all tables by enabling RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE sos_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 👤 Profiles: Everyone can read basic info (for directory), Owners can update own
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- 🚶 Visitors: 
-- Residents see their own visitors. Guards see all (to manage gate).
CREATE POLICY "Residents view own visitors" ON visitors FOR SELECT USING (auth.uid() = resident_id);
CREATE POLICY "Guards view all visitors" ON visitors FOR SELECT 
    USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('guard', 'admin')));
CREATE POLICY "Guards insert visitors" ON visitors FOR INSERT 
    WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('guard', 'admin')));
CREATE POLICY "Residents/Guards update visitors" ON visitors FOR UPDATE USING (
    auth.uid() = resident_id OR 
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('guard', 'admin'))
);

-- 🔔 Notifications: Only owner can see/update
CREATE POLICY "Users manage own notifications" ON notifications 
    USING (auth.uid() = user_id);

-- ⚠️ Complaints: Residents see own, Admins see all
CREATE POLICY "Residents view own complaints" ON complaints FOR SELECT USING (auth.uid() = resident_id);
CREATE POLICY "Admins view all complaints" ON complaints FOR SELECT 
    USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Residents create complaints" ON complaints FOR INSERT WITH CHECK (auth.uid() = resident_id);
CREATE POLICY "Admins update complaints" ON complaints FOR UPDATE 
    USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- 🚨 SOS: Guards/Admins see active. Residents see own.
CREATE POLICY "SOS Visibility" ON sos_alerts FOR SELECT USING (
    auth.uid() = resident_id OR 
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('guard', 'admin'))
);
CREATE POLICY "Users trigger SOS" ON sos_alerts FOR INSERT WITH CHECK (auth.uid() = resident_id);
CREATE POLICY "Admins resolve SOS" ON sos_alerts FOR UPDATE 
    USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('guard', 'admin')));


-- ================================================================================================
-- 4. FUNCTIONS & TRIGGERS
-- ================================================================================================

-- ⚡ Handle New User Registration
-- Automatically creates a profile row when a user signs up via Auth
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, role)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'name', 'resident');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger the function on auth.users insert
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 🔔 Realtime Notification Trigger (Example)
-- Can be used to invoke Edge Functions via Webhooks usually, 
-- but here we rely on the App logic to allow flexible Notification Service.

-- ================================================================================================
-- ✅ SCHEMA COMPLETE
-- ================================================================================================
