include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error prevention
    - avoid_print
    # - avoid_dynamic_calls # Too strict for now due to Supabase dynamic data
    - await_only_futures
    - unawaited_futures
    - control_flow_in_finally
    - empty_statements
    
    # Style
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - sort_child_properties_last
    - curly_braces_in_flow_control_structures
    
    # Coding Standard
    - camel_case_types
    - library_private_types_in_public_api
    - no_duplicate_case_values
    - null_closures
    - prefer_contains
    - prefer_is_empty
    - prefer_is_not_empty
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - use_rethrow_when_possible
    - valid_regexps
    
    # Performance
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_build_context_synchronously
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
